### ISSUE TITLE
Missing prereq specifications

### ISSUE THREAD

**Issue by eserte** [regru/lingua-ru-num2word#1]
It seems that Test::More::UTF8 and lib::abs are missing in the PREREQ_PM specification. See http://matrix.cpantesters.org/?dist=Lingua-RU-Num2Word%200.001 for a pass/fail overview and
http://analysis.cpantesters.org/solved?distv=Lingua-RU-Num2Word-0.001 for a fail report analysis.

**Comment by imago-storm** [comment]
Thank you, fixed
